# Generated by Django 4.2.1 on 2023-12-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_data',
            name='Bungy_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='Cab',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='Droplocation',
            field=models.CharField(default='No', max_length=150),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='Meal',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='Mount',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='Mount_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='Picklocation',
            field=models.CharField(default='No', max_length=150),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='River_number',
            field=models.IntegerField(default=0),
        ),
    ]
