# Generated by Django 4.2.1 on 2023-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_app', '0002_alter_trip_data_bungy_number_alter_trip_data_cab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_data',
            name='Bungy',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='River',
            field=models.CharField(default='No', max_length=50),
        ),
    ]
