# Generated by Django 4.2.1 on 2023-12-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_app', '0003_alter_trip_data_bungy_alter_trip_data_river'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_data',
            name='Cab',
            field=models.CharField(max_length=10),
        ),
    ]
