# Generated by Django 4.2.1 on 2023-12-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller_app', '0005_alter_trip_data_cab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_data',
            name='Bungy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='Cab',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='Droplocation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='Meal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='Mount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='Picklocation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='trip_data',
            name='River',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
