from django.db import models
from django.contrib.auth.models import User

class user1(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=100)
    state = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=15) 

class trip_data(models.Model):
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    First_name = models.CharField(max_length=50)
    Last_name = models.CharField(max_length=50)
    Date_of_birth = models.DateField()
    Phone_number = models.CharField(max_length=15)
    Email = models.EmailField(max_length=100)
    Address = models.CharField(max_length=150)
    State = models.CharField(max_length=50)
    Zip_code = models.CharField(max_length=20)
    Document = models.CharField(max_length=20)
    Document_number = models.CharField(max_length=50)
    Holiday_place = models.CharField(max_length=50)
    Child = models.IntegerField(default=0)
    Adult = models.IntegerField(default=0)
    Old = models.IntegerField(default=0)
    Guest = models.TextField()
    Guest_Doc_number = models.TextField()
    Check_in = models.DateField()
    Check_out = models.DateField()
    Meal = models.CharField(max_length=10, null=True, blank=True)
    Star = models.IntegerField(default=1)
    Mount = models.CharField(max_length=50, null=True, blank=True)
    Mount_number = models.IntegerField(default=0)
    Bungy = models.CharField(max_length=50, null=True, blank=True)
    Bungy_number = models.IntegerField(default=0)
    River = models.CharField(max_length=50, null=True, blank=True)
    River_number = models.IntegerField(default=0)
    Cab = models.CharField(max_length=10, null=True, blank=True)
    Picklocation = models.CharField(max_length=150, null=True, blank=True)
    Droplocation = models.CharField(max_length=150, null=True, blank=True)
